### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by erice4** [NCCA/OctreeAbstract#1]
In file included from /opt/qt/5.5/gcc_64/include/QtGui/QOpenGLContext:1:0,
                 from /opt/qt/5.5/gcc_64/include/QtGui/qopenglwindow.h:42,
                 from /opt/qt/5.5/gcc_64/include/QtGui/QOpenGLWindow:1,
                 from include/NGLScene.h:11,
                 from src/NGLScene.cpp:4:
/opt/qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:49:2: warning: #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined [-Wcpp]
 #warning qopenglfunctions.h is not compatible with GLEW, GLEW defines will be undefined
  ^
/opt/qt/5.5/gcc_64/include/QtGui/qopenglcontext.h:50:2: warning: #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h [-Wcpp]
 #warning To use GLEW with Qt, do not include <qopengl.h> or <QOpenGLFunctions> after glew.h
  ^
In file included from include/NGLScene.h:8:0,
                 from src/NGLScene.cpp:4:
include/Scene.h:90:5: error: 'unique_ptr' in namespace 'std' does not name a type
     std::unique_ptr<ParticleOctree>  collisionTree;
     ^
In file included from src/NGLScene.cpp:4:0:
include/NGLScene.h:119:5: error: 'unique_ptr' in namespace 'std' does not name a type
     std::unique_ptr<Scene> m_scene;
     ^
include/NGLScene.h:121:5: error: 'unique_ptr' in namespace 'std' does not name a type
     std::unique_ptrngl::Text m_text;
     ^
include/NGLScene.h: In member function 'void NGLScene::clearParticles()':
include/NGLScene.h:53:34: error: 'm_scene' was not declared in this scope
     inline void clearParticles(){m_scene->clearParticles(); }
                                  ^
src/NGLScene.cpp: In member function 'virtual void NGLScene::initializeGL()':
src/NGLScene.cpp:85:3: error: 'm_scene' was not declared in this scope
   m_scene.reset(new  Scene(&m_transform,&m_cam));
   ^
src/NGLScene.cpp:92:3: error: 'm_text' was not declared in this scope
   m_text.reset(new ngl::Text(QFont("Arial",14)));
   ^
src/NGLScene.cpp: In member function 'virtual void NGLScene::paintGL()':
src/NGLScene.cpp:112:3: error: 'm_text' was not declared in this scope
   m_text->setScreenSize(width(),height());
   ^
src/NGLScene.cpp:136:3: error: 'm_scene' was not declared in this scope
   m_scene->draw(m_mouseGlobalTX);
   ^
src/NGLScene.cpp: In member function 'void NGLScene::addParticles()':
src/NGLScene.cpp:149:5: error: 'm_scene' was not declared in this scope
     m_scene->clearParticles();
     ^
src/NGLScene.cpp: In member function 'virtual void NGLScene::timerEvent(QTimerEvent_)':
src/NGLScene.cpp:180:9: error: 'm_scene' was not declared in this scope
         m_scene->update();
         ^
make: *_\* [obj/NGLScene.o] Error 1
12:13:49: The process "/usr/bin/make" exited with code 2.
Error while building/deploying project OctreeAbstract (kit: Desktop Qt 5.5.0 GCC 64bit)
When executing step "Make"

**Comment by jmacey** [comment]
needed to add #include <memory> to NGLScene.h as it seems the default qmake in the shell uses g++ and this doesn't default to including it whereas clang++ on mac does.
